# Site settings
email: draganakostic@gmail.com
baseurl: "draganakostic.com"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: mio sito personale
description: mio sito personale
url: "draganakostic.com"
twitter_username:
default_img: /img/gg.jpg

# Profile settings
name: Dragana Kostic
profile_img: /img/gg.jpg
profile: "Sono dottoressa in Scienze dell’Architettura. Attualmente mi muovo tra Venezia e Monterosso al Mare (Cinque Terre). Sono sempre alla ricerca di metodi e occasioni per approfondire la ricerca e migliorare lo sviluppo dei progetti artistico-architettonici. Le competenze che offro e propongo sono principalmente la modellazione tridimensionale e l’elaborazione grafica: la progettazione preliminare ed il rilievo architettonico (anche online). Per qualsiasi richiesta non esitate a contattarmi."
social:
  facebook: https://www.facebook.com/dragana.kostic.71
  linkedin: https://www.linkedin.com/in/dragana-kostic-87268a44

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock","photoshop"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
