# Site settings
email: draganakostic@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: mio sito personale
description:
url: "draganakostic.com"
twitter_username:
default_img:

# Profile settings
name: Dragana Kostic
profile_img: /img/gg.jpg
profile: Sono dott.ssa in Scienze dell`architettura attualmente situata tra i due comuni Monterosso al mare e Venezia. Sono sempre alla ricerca per i migliori progetti. Sarei lieto di poter approfondire delle ricerche e di sviluppare al meglio progetto artistico architettonnico. Le competenze che offro e propongo di svillupare sono la modellazione tridimensionale e l'elaborazione grafica.La progetazione architettonica preliminare ed il rilievo architettonico,anche online. Per qualsiasi richiesta non esitate a contattarmi.
social:
  facebook: https://www.facebook.com/dragana.kostic.71
  linkedin: https://www.linkedin.com/in/dragana-kostic-87268a44

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock","photoshop"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
